Manifest json changes
ao-spirogyra/extended-browser-history-chrome-extension pull request #8
Opened 2021-02-09 12:23 UTC by takumimunemura

manifest.jsonの1.名称を変更("name" : ""の変更) 2.アイコンの追加("icons:以下4行を追加 3

2021-02-10 04:19 UTC, ao-spirogyra requested changes
アイコンにカーソルを合わせたときの挙動は要変更だと思いました

2021-02-10 04:19 UTC, ao-spirogyra commented on manifest.json
> +    "default_title": "mewmew"
かわいくていい感じですがdefault_titleという名前にある通りtitle表示されてほしいです

2021-02-10 04:19 UTC, ao-spirogyra commented on manifest.json
> +  "name": "traveller's dialy",
この名前いいですね！！

2021-02-10 04:19 UTC, ao-spirogyra commented on manifest.json
> +    "16" : "images/sampleicon.png",
@takumimunemura アイコンってどうやって作りました(or どこから持ってきました)？
一応著作権とか気にしておきたいです

2021-02-15 05:28 UTC, takumimunemura commented on manifest.json
> +    "default_title": "mewmew"
sad

2021-02-15 05:32 UTC, takumimunemura commented on manifest.json
> +    "16" : "images/sampleicon.png",
本，フリー素材と検索して出てきた　(https://icon-pit.com/pictogram/4691)から拝借しました。

2021-02-15 05:33 UTC, takumimunemura commented on manifest.json
> +  "name": "traveller's dialy",
啓示を受けました

2021-02-15 05:41 UTC, ao-spirogyra approved these changes

2021-02-15 05:41 UTC, merged